Implement input action
TNorbury/command_palette pull request #35
Opened 2023-06-26 04:17 UTC by NishiyamaPedro

2023-09-24 22:01 UTC, TNorbury commented
Thank you for this pull request, and I apologize that I'm just now seeing it. I will try to take a look at it in the coming weeks.

Would you be able to add one of these types of actions to the example (see [here](https://github.com/TNorbury/command_palette/blob/main/example/lib/main.dart#L67)). That way I can have an idea of how it's supposed to be used.

Thanks!

2023-09-29 14:57 UTC, TNorbury requested changes
Thanks again for this PR. It looks really great, just a few housekeeping items, in addition to what I mentioned above.

2023-09-29 14:57 UTC, TNorbury commented on lib/src/controller/command_palette_controller.dart
> +      return;
Wrap in brackets
```suggestion
    if (currentlySelectedAction?.actionType == CommandPaletteActionType.input) {
      return;
    }
```

2023-09-29 14:57 UTC, TNorbury commented on lib/src/models/command_palette_action.dart
> +  input
Add this comment
```suggestion
  /// Upon being selected the user will be given a text field that they can enter text into and submit.
  /// The entered text will then be passed to the relevant callback
  input
```

2023-09-29 16:44 UTC, NishiyamaPedro commented
Thanks for the review. I've made the requested changes and added a basic example.

2023-10-30 22:43 UTC, merged

2023-10-30 22:43 UTC, TNorbury commented
Awesome, thanks for the changes!